# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Malware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='inforecord',
            name='malware',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Malware'),
        ),
    ]
