# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160207_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='value',
            field=models.CharField(max_length=200),
        ),
    ]
