# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160207_1457'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InfoRecord',
            new_name='Data',
        ),
    ]
