# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='data',
            field=models.FileField(upload_to=b''),
        ),
    ]
