# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20160210_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='data_chunks_sent',
            field=models.IntegerField(default=1),
        ),
    ]
