# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_file_data_chunks_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='type',
        ),
        migrations.RemoveField(
            model_name='data',
            name='value',
        ),
        migrations.AddField(
            model_name='data',
            name='data',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='data',
            name='data_chunks_sent',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='data',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='command',
            name='type',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='command',
            name='value',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='file',
            name='data',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
