# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20160210_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='malware',
            name='teammates',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='malware',
            name='token',
            field=models.CharField(default='', max_length=120),
        ),
    ]
