# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20160210_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='data_chunks_sent',
        ),
        migrations.AlterField(
            model_name='file',
            name='data',
            field=models.FileField(upload_to=b''),
        ),
    ]
