# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20160210_1539'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='FileItem',
        ),
    ]
