# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20160211_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileitem',
            name='data',
            field=models.TextField(default=''),
        ),
    ]
